name: Cypress Tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install http-server and Dependencies
        run: |
          npm install
          npm install http-server -g

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          project: .
          start: http-server . -p 8080
          wait-on: "http://localhost:8080"
          wait-on-timeout: 60
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}

      - name: Notify Discord
        if: always()
        run: |
          curl -H "Content-Type: application/json" \
          -d "{\"content\": \"Projeto 01: Testes finalizados. Status: ${{ job.status }}\"}" \
          ${{ secrets.DISCORD_WEBHOOK }}
